---
title: "Appendix A - [TEMPLATE] Marine Park Natural Values Report"
subtitle: "South-west Marine Parks Network"
format:
  pdf:
    output-file: "Project 4.21-[TEMPLATE]-2-Appendix A-q-Natural values.pdf"
    fig-pos: 'H'
    geometry: 
      - top=2cm
      - bottom=2.5cm
      - left=2cm
      - right=2cm
    include-in-header:
      text: |
        \usepackage{caption}
        \usepackage{float}
        \usepackage{chngcntr}
        \newcounter{metric}
        \counterwithin*{figure}{metric}
        \captionsetup{format=plain, indention=0pt}
toc: true
execute:
  echo: false
  warning: false
  message: false
post-render: 10_move-pdf.R
---

```{r}
#| include: false
library(here)
library(ggplot2)
library(knitr)
library(terra)
library(tidyterra)
library(cowplot)
library(png)
library(grid)
library(tidytext)
library(ggtext)

# Year suffix on the fish spatial-metric PNGs (script 08 saves them with
# paste(years, collapse = "-")). Set once per park to match the [ABBR] survey
# years used throughout this appendix.
yr_suffix <- "YYYY-YYYY"
```

# Natural Values

Understanding of natural values

## Benthic ecosystem extent

### Dominant habitat types

```{r}
#| fig-width: 8
#| fig-height: 5
#| fig-cap: "Predicted dominant habitat type from stereo-BRUV groundtruthing. Commonwealth marine park boundaries are shown. The red line delimits state and commonwealth waters. Bathymetric contour at 30 m is shown."
p_cat <- readRDS(here("plots/[TEMPLATE]/habitat/[TEMPLATE]AMP_predicted-habitat-categorical.rds"))
p_cat
```

{{< pagebreak >}}

### Habitat distribution and probability

```{r}
#| fig-width: 8
#| fig-height: 7
#| fig-cap: "Predicted habitat distribution probability and uncertainty from stereo-BRUV groundtruthing. Commonwealth marine park boundaries are shown. The red line delimits state and commonwealth waters. Bathymetric contour at 30 m is shown."
img_path <- here("plots/[TEMPLATE]/habitat/[TEMPLATE]_predicted-dominant-benthos-and-combined-se_2014-2024.png")
img <- png::readPNG(img_path)
grid::grid.raster(img)
```

{{< pagebreak >}}

### Observations

```{r}
#| fig-width: 8
#| fig-height: 4
#| fig-cap: "Habitat classes observed in spatially balanced stereo-BRUV and drop-camera imagery visualised as spatial pie charts. Commonwealth marine park boundaries are shown. The red line delimits state and commonwealth waters. Bathymetric contour at 30 m is shown."
img <- png::readPNG(here("plots/[TEMPLATE]/habitat/[TEMPLATE]AMP_scatterpie.png"))
grid::grid.raster(img)
```

{{< pagebreak >}}

## Benchmarks of benthic natural values

```{=latex}
% Continue the running figure number into the benchmark sections, then switch
% to <metric>.<plot> numbering. `metric` is seeded to the last benthic-extent
% figure number so the majors carry on sequentially (4, 5, 6, ...).
\setcounter{metric}{\value{figure}}
\renewcommand{\thefigure}{\arabic{metric}.\arabic{figure}}
```

### Sand

```{=latex}
\stepcounter{metric}
```



```{r}
#| fig-width: 6
#| fig-height: 3
#| fig-cap: "Sand: temporal plots by depth contour from stereo-BRUV groundtruthing. [ABBR] = [TEMPLATE] Marine Park (Commonwealth)."
p_control <- readRDS(here("plots/[TEMPLATE]/habitat/[TEMPLATE]AMP_control-plot_sand.rds"))
p_control
```

{{< pagebreak >}}



```{r}
#| fig-width: 8
#| fig-height: 5.5
#| fig-cap: "Sand: spatial plots of distribution probability and uncertainty from stereo-BRUV groundtruthing. [ABBR] = [TEMPLATE] Marine Park (Commonwealth). Commonwealth marine park boundaries are shown. The red line delimits state and commonwealth waters. Bathymetric contour at 30 m is shown."
img <- png::readPNG(here("plots/[TEMPLATE]/habitat/[TEMPLATE]AMP_predicted-individual-habitat_sand.png"))
grid::grid.raster(img)
```

{{< pagebreak >}}

### Macroalgae

```{=latex}
\stepcounter{metric}
```



```{r}
#| fig-width: 6
#| fig-height: 3
#| fig-cap: "Macroalgae: temporal plots by depth contour from stereo-BRUV groundtruthing. [ABBR] = [TEMPLATE] Marine Park (Commonwealth)."
p_control <- readRDS(here("plots/[TEMPLATE]/habitat/[TEMPLATE]AMP_control-plot_macroalgae.rds"))
p_control
```

{{< pagebreak >}}



```{r}
#| fig-width: 8
#| fig-height: 5.5
#| fig-cap: "Macroalgae: spatial plots of distribution probability and uncertainty from stereo-BRUV groundtruthing. [ABBR] = [TEMPLATE] Marine Park (Commonwealth). Commonwealth marine park boundaries are shown. The red line delimits state and commonwealth waters. Bathymetric contour at 30 m is shown."
img <- png::readPNG(here("plots/[TEMPLATE]/habitat/[TEMPLATE]AMP_predicted-individual-habitat_macroalgae.png"))
grid::grid.raster(img)
```

{{< pagebreak >}}

### Sessile invertebrates

```{=latex}
\stepcounter{metric}
```



```{r}
#| fig-width: 6
#| fig-height: 3
#| fig-cap: "Sessile invertebrates: temporal plots by depth contour from stereo-BRUV groundtruthing. [ABBR] = [TEMPLATE] Marine Park (Commonwealth)."
p_control <- readRDS(here("plots/[TEMPLATE]/habitat/[TEMPLATE]AMP_control-plot_sessile-invertebrates.rds"))
p_control
```



```{r}
#| fig-width: 8
#| fig-height: 5.5
#| fig-cap: "Sessile invertebrates: spatial plots of distribution probability and uncertainty from stereo-BRUV groundtruthing. [ABBR] = [TEMPLATE] Marine Park (Commonwealth). Commonwealth marine park boundaries are shown. The red line delimits state and commonwealth waters. Bathymetric contour at 30 m is shown."
img <- png::readPNG(here("plots/[TEMPLATE]/habitat/[TEMPLATE]AMP_predicted-individual-habitat_sessile-invertebrates.png"))
grid::grid.raster(img)
```

{{< pagebreak >}}

## Benchmarks of demersal fish natural values

### Species richness

```{=latex}
\stepcounter{metric}
```



```{r}
#| fig-width: 6
#| fig-height: 3
#| fig-cap: "Demersal fish - Species richness: benchmark plots by zone and depth contour from stereo-BRUV groundtruthing. [ABBR] = [TEMPLATE] Marine Park (Commonwealth)."
p_control <- readRDS(here("plots/[TEMPLATE]/fish/[TEMPLATE]AMP_control-plot_species-richness-per-bruv.rds"))
p_control
```

```{r}
#| fig-width: 6
#| fig-height: 3
#| fig-cap: "Demersal fish - Species richness: species accumulation curve by year from stereo-BRUV groundtruthing. [ABBR] = [TEMPLATE] Marine Park (Commonwealth)."
p_bar <- readRDS(here("plots/[TEMPLATE]/fish/[TEMPLATE]AMP_SAC-sample.rds"))
p_bar
```

{{< pagebreak >}}



```{r}
#| fig-width: 7
#| fig-height: 4
#| fig-cap: "Demersal fish - Species richness: spatial plots of distribution probability and uncertainty from stereo-BRUV groundtruthing. Commonwealth marine park boundaries are shown. The red line delimits state and commonwealth waters. Bathymetric contour at 30 m is shown."
img <- png::readPNG(here(paste0("plots/[TEMPLATE]/fish/[TEMPLATE]AMP_predicted-individual-fish-metric_whole-assemblage_", yr_suffix, ".png")))
grid::grid.raster(img)
```

{{< pagebreak >}}

### Total abundance

```{=latex}
\stepcounter{metric}
```



```{r}
#| fig-width: 6
#| fig-height: 3
#| fig-cap: "Demersal fish - Total abundance: benchmark plots by zone and depth contour from stereo-BRUV groundtruthing. [ABBR] = [TEMPLATE] Marine Park (Commonwealth)."
p_control <- readRDS(here("plots/[TEMPLATE]/fish/[TEMPLATE]AMP_control-plot_total-abundance-per-bruv.rds"))
p_control
```

```{r}
#| fig-width: 6
#| fig-height: 3
#| fig-cap: "Demersal fish - Total abundance: top 10 most abundant species (pooled across deployments) from stereo-BRUV groundtruthing. [ABBR] = [TEMPLATE] Marine Park (Commonwealth)."
p_bar <- readRDS(here("plots/[TEMPLATE]/fish/[TEMPLATE]AMP_top_maxn_bar_plot.rds"))
p_bar
```

{{< pagebreak >}}



```{r}
#| fig-width: 7
#| fig-height: 4
#| fig-cap: "Demersal fish - Total abundance: spatial plots of distribution probability and uncertainty from stereo-BRUV groundtruthing. Commonwealth marine park boundaries are shown. The red line delimits state and commonwealth waters. Bathymetric contour at 30 m is shown."
img <- png::readPNG(here(paste0("plots/[TEMPLATE]/fish/[TEMPLATE]AMP_predicted-individual-fish-metric_total-abundance_", yr_suffix, ".png")))
grid::grid.raster(img)
```

{{< pagebreak >}}

### Large Reef Fish Index\*

```{=latex}
\stepcounter{metric}
```



```{r}
#| fig-width: 6
#| fig-height: 3
#| fig-cap: "Demersal fish - Large Reef Fish Index\\*: benchmark plots by zone and depth contour from stereo-BRUV groundtruthing. [ABBR] = [TEMPLATE] Marine Park (Commonwealth). \\*Large Reef Fish Index representing the biomass of all fish greater than 20 cm (B20) has been adapted here for stereo-BRUV data by removing sharks and rays."
p_control <- readRDS(here("plots/[TEMPLATE]/fish/[TEMPLATE]AMP_control-plot_large-reef-fish-index-biomass-g-per-bruv.rds"))
p_control
```

```{r}
#| fig-width: 6
#| fig-height: 3
#| fig-cap: "Demersal fish - Large Reef Fish Index\\*: top 10 greatest biomass species (pooled across deployments) from stereo-BRUV groundtruthing. [ABBR] = [TEMPLATE] Marine Park (Commonwealth)."
p_bar <- readRDS(here("plots/[TEMPLATE]/fish/[TEMPLATE]AMP_top_b20_bar_plot.rds"))
p_bar
```

{{< pagebreak >}}



```{r}
#| fig-width: 7
#| fig-height: 4
#| fig-cap: "Demersal fish - Large Reef Fish Index\\*: spatial plots of distribution probability and uncertainty from stereo-BRUV groundtruthing. Commonwealth marine park boundaries are shown. The red line delimits state and commonwealth waters. Bathymetric contour at 30 m is shown."
img <- png::readPNG(here(paste0("plots/[TEMPLATE]/fish/[TEMPLATE]AMP_predicted-individual-fish-metric_large-reef-fish-index_", yr_suffix, ".png")))
grid::grid.raster(img)
```

{{< pagebreak >}}

### Reef fish thermal index

```{=latex}
\stepcounter{metric}
```



```{r}
#| fig-width: 6
#| fig-height: 3
#| fig-cap: "Demersal fish - Reef Fish Thermal Index: benchmark plots by zone and depth contour, with monthly sea surface temperature (black line, grey band = SD) overlaid, from stereo-BRUV groundtruthing. [ABBR] = [TEMPLATE] Marine Park (Commonwealth)."
p_control <- readRDS(here("plots/[TEMPLATE]/fish/[TEMPLATE]AMP_control-plot_community-thermal-index-c.rds"))
p_control
```

```{r}
#| fig-width: 6
#| fig-height: 3
#| fig-cap: "Demersal fish - Reef Fish Thermal Index: species thermal niche of top 10 most abundant species (pooled across deployments) from stereo-BRUV groundtruthing. [ABBR] = [TEMPLATE] Marine Park (Commonwealth)."
p_bar <- readRDS(here("plots/[TEMPLATE]/fish/[TEMPLATE]AMP_top_maxn_cti_bar_plot.rds"))
p_bar
```

{{< pagebreak >}}



```{r}
#| fig-width: 7
#| fig-height: 4
#| fig-cap: "Demersal fish - Reef Fish Thermal Index: spatial plots of distribution probability and uncertainty from stereo-BRUV groundtruthing. Commonwealth marine park boundaries are shown. The red line delimits state and commonwealth waters. Bathymetric contour at 30 m is shown."
img <- png::readPNG(here(paste0("plots/[TEMPLATE]/fish/[TEMPLATE]AMP_predicted-individual-fish-metric_cti_", yr_suffix, ".png")))
grid::grid.raster(img)
```
