name: "TEMPLATE"
park: "geographe"
years: ["2023", "2024"]      # EVERY survey year
combine_benthos: false       # true = pool benthos years into ONE
                             # Combine benthos if years have samples in different spatial areas
